#+TITLE: MIEEIC Thesis writing
#+AUTHOR: José Pires
#+DATE: [2024-05-06 seg 20:20]
#+EMAIL: a50178@alunos.uminho.pt

#+LATEX_COMPILER: xelatex

* TOC :noexport::TOC_3:
- [[#preamble][Preamble]]
  - [[#git-workflow][Git Workflow]]
  - [[#template-struct][Template Struct]]
  - [[#template-organization][Template Organization]]
  - [[#template-macros][Template macros]]
  - [[#folder-struct][Folder struct]]
  - [[#update-repo][Update repo]]
  - [[#packages][Packages]]
    - [[#fail-to-compile-caption-and-subcaption][Fail to compile: caption and subcaption]]
- [[#formatting][Formatting]]
  - [[#normas-para-a-formatação-gráfica][Normas para a formatação gráfica]]
  - [[#normas-para-o-depósito-no-repositorium][Normas para o depósito no RepositoriUM]]
- [[#tools][Tools]]
  - [[#notebooklm][Notebooklm]]
- [[#research][Research]]
  - [[#my-thesis-gaps][My thesis gaps]]
- [[#writing][Writing]]
  - [[#-done-title][✔ DONE Title]]
  - [[#abstract][Abstract]]
  - [[#-done-ask-for-permissions-for-figures-httpswwwresearchgatenetpostdo_i_need_a_permission_to_copy_any_figure_from_a_research_article_for_my_review_article5de8fdb7f0fb623dd7346896citationdownload][✔ DONE Ask for permissions for figures https://www.researchgate.net/post/Do_I_need_a_permission_to_copy_any_figure_from_a_research_article_for_my_review_article/5de8fdb7f0fb623dd7346896/citation/download]]
    - [[#licence-footnote][Licence footnote]]
  - [[#-done-chapter-style][✔ DONE Chapter style]]
  - [[#intro-14][Intro]]
  - [[#state-of-the-art-16][State of the Art]]
    - [[#uav-intro][UAV Intro]]
    - [[#security-concerns][Security concerns]]
    - [[#diagrams-uav][Diagrams UAV]]
    - [[#autopilot][Autopilot]]
    - [[#px4][PX4]]

* Preamble
** Git Workflow
[[id:B5099895-B69D-4599-9295-DEE12EA81B89][src]]
   #+begin_src markdown
    > When you push, do so on `origin` with `git push origin`.
   
    > When you want to pull changes from `upstream` you can just fetch the remote and rebase on top of your work.
    ```bash
      git fetch upstream
      git rebase upstream/master
      ```
      And solve the conflicts if any
   #+end_src
** Template Struct
1) *Fonts*:
   1) Download NewsGott fonts from [[https://github.com/joaomlourenco/novathesis-extras/tree/main/Fonts][Novathesis-extras]] repo
   2) Place it in: =/FontStyles/Fonts=
2) *Compilation*: Compile the document with you favorite LaTeX processor
   (pdfLaTeX, XeLaTeX or LuaLaTeX):
   - The main file is named “template.tex”.
   - Compilation step:
     - load it in your favorite LaTeX text editor or
     - compile it in the terminal with latexmk -pdf template.
     - run =make xe=: *IMPORTANT*
       - UM template requires NewsGott fonts which require Xelatex to run
   - If you use a LaTeX text editor, please notice that the NOVAthesis template
     uses biber and not bibtex to process the bibliography, which means that most
     probably you have to open the Editor Preferences and somewhere (depends on
     the Editor) chage bibtex to biber.
   - If Murphy is elsewhere, LaTeX will create the file “template.pdf”.
3) *Writing*: Edit the files in the “Config” folder [3/8]:
   1) [X] =0_memoir.tex=: Options specific for the memoir package. Don't touch
      this file unless you know what you are doing!
   2) [X] =1_novathesis.tex=: Configure the template, i.e., the document type,
      the school, etc.
   3) [X] =2_biblatex.tex=: Configure the bibliography.
   4) [ ] =3_cover.tex=: Configure cover contents (e.g., author's name,
      thesis/dissertation title, advisers, committee, etc)
      1) [ ] Fontes de financiamento
      2) [ ] Committee
   5) [ ] =4_files.tex=: Configure the the files for chapters, appendices,
      annexes, etc...
   6) [ ] =5_packages.tex=: Configure additional packages and commands
   7) [ ] =6_list_of.tex=: Configure the lists to be printed (table of contents,
      list of figures, list of tables, list of listings, etc). Don't touch this
      file unless you know what you are doing!
   8) =9_nova_fct.tex=: Configuration specific to nova/fct
   9) =9_nova_ims.tex=: Configuration specific to nova/ims
   10) =9_nova_itqb.tex=: Configuration specific to nova/itqb
   11) =9_ulisboa_fmv.tex=: Configuration specific to ulisboa/fmv
   12) [ ] =9_uminho.tex=: Configuration specific to uminho (all schools)
** Template Organization                                          :Important:
see [[pdfview:/Users/zemiguel/OneDrive - Universidade do Minho/Documents/Univ/PhD/writing/PhD-Mech-Thesis/template_novathesis.pdf::18][template_novathesis.pdf]]

Chapters: [0/3]
1) [ ] Introduces the Novathesis template and how it is organized
2) [ ] specific instructions on how to use the novathesis template
3) [ ] Examples and hints on how to write your text
   
  Front Matter (1)
  Cover (1)
  Front Page (3)
  Copyright (4)
  Acknowledgements (5)
  Statement (6)
  Quote (7)
  Resumo (8)
  Abstract (9)
  Contents (10)
  List of Figures (12)
  List of Tables (13)
  Glossary (14)
  Acronyms (15)
  Symbols (16)
  Chemical Symbols (17)
1 Introduction (18)
  1.1 If You Use this Template… (18)
    1.1.1 Your Time is Precious (18)
    1.1.2 Recognition (19)
  1.2 The NOVAthesis template (19)
  1.3 Getting Started (24)
    1.3.1 Using Overleaf (24)
    1.3.2 Using a Local LaTeX Installation (25)
  1.4 Getting Help (25)
    1.4.1 Suggestions, Bugs and Feature Requests (26)
  1.5 Donors (26)
  1.6 Disclaimer (26)
2 NOVAthesis Template User's Manual (27)
  2.1 Introduction (27)
  2.2 Quick Start (27)
    2.2.1 With a Local LaTeX Installation (27)
    2.2.2 With a Remote Cloud-based Service (30)
  2.3 [[pdfview:/Users/zemiguel/OneDrive - Universidade do Minho/Documents/Univ/PhD/writing/PhD-Mech-Thesis/template_novathesis.pdf::30][Folder and Files]] (30)
  2.4 [[pdfview:/Users/zemiguel/OneDrive - Universidade do Minho/Documents/Univ/PhD/writing/PhD-Mech-Thesis/template_novathesis.pdf::31][novathesis.cls Class Options]] (31)
  2.5 Additional considerations about the class options (32)
    2.5.1 The main language (32)
    2.5.2 Class of Text (33)
    2.5.3 Printing (33)
    2.5.4 Font Size (34)
    2.5.5 Text Encoding (34)
    2.5.6 Examples (34)
  2.6 How to Write Using LaTeX (34)
  2.7 Example glossary, acronyms, and symbols (34)
3 A Short LaTeX Tutorial with Examples (36)
  3.1 Document Structure (36)
  3.2 Dealing with Bibliography (36)
  3.3 Inserting Tables (36)
  3.4 Importing Images (36)
  3.5 Floats, Figures and Captions (36)
  3.6 Text Formatting (38)
  3.7 Generating PDFs from LaTeX (38)
    3.7.1 Generating PDFs with pdflatex (38)
    3.7.2 Dealing with Images (39)
    3.7.3 Creating Source Files Compatible with both latex and pdflatex (39)
  3.8 Equações (41)
  3.9 Test for listings (41)
  3.10 Test for algorithms (44)
Bibliography (45)
A NOVAthesis covers showcase (47)
B Appendix 2 Lorem Ipsum (48)
I Annex 1 Lorem Ipsum (50)
Back Matter (52)
  Back Cover (53)
  
** Template macros                                                :Important:
#+begin_src latex
  % Syntax - all arguments are optional and can be omitted from the last to the first
  % \begin{ntquote}
	  % [max width of citation box]
	  % [author name]
	  % [where/source]
	  % [profession]
	  % [lang]
  % YOUR TEXT HERE
  % \end{ntquote}
  
\begin{ntquote}[8cm][Galileo][Somewhere in a book or speach][Astronomer, physicist and engineer][en]
  You cannot teach a man anything; you can only help him discover it in himself.%
\end{ntquote}
#+end_src
** Folder struct
- [[file:writing][folder]]
- [[file:writing/Bibliography][Bibliography]]: bibliography references spread through multiple files
- [[file:writing/Chapters][Chapters]]: thesis's chapters
- [[file:Chapters-PhD][Chapters-PhD]]: PhD thesis chapters to help the writing
- [[file:writing/Config][Config]]: configuration files for the thesis formatting
  0) [@0] [[file:writing/Config/0_memoir.tex][memoir.tex]]: defines paper size and font size
  1) [[file:writing/Config/1_novathesis.tex][novathesis.tex]]: actual template configuration
  2) [[file:writing/Config/2_biblatex.tex][biblatex.tex]]: bibliography configuration
  3) cover.tex: cover configuration 
  4) files.tex: where we define what files/chapters must be added to the thesis
  5) packages.tex: extra packages to be added
  6) list_of.tex: lists used in the thesis, e.g., TOC, figures, tables,
     listings, acronyms
  7) 9_uminho.tex
- [[file:writing/doc][doc]]: LaTeX template documentation
  - UM formatting norms
  - chapter styles
- [[file:writing/img][img]]: images used in the thesis, in multiple formats (.eps, .jpg, .pdf, .png,
  .svg)
- [[file:writing/listing][listing]]: code snippets
- [[file:writing/NOVAthesisFiles][NovathesisFiles]]: template files
- [[file:writing/pdf][pdf]]: extra pages that must be added as PDF, like appendices, but also the
  *license* and the *integrity statement*
- [[file:writing/sty][sty]]: styles used in the thesis for things like *listings*
- [[file:writing/tables][tables]]: LaTeX tables generated externally

** Update repo
Last time I used the =template_novathesis=, and more specifically my freezed
version of it, it was more than 1 year ago (Jan 2023).
- Meanwhile, I wrote my PhD thesis using it, with some improvements
- Furthermore, the template has also evolved
- Thus, it is useful to update the repo
- Furthermore, it can also be useful to add it as a submodule of the current
  repository


*Tasks* [2/7]:
1) [X] Fork the current version of the Novathesis template
2) [X] Compile it
3) [ ] Update it with my current state of the thesis
4) [ ] Compile it again
5) [ ] Update it with some tweaks from my PhD thesis
6) [ ] Compile it again
7) [ ] Add it as submodule of the current repo
  
** Packages

*** Fail to compile: caption and subcaption                         :Problem:

I had to comment the lines below
#+begin_src latex
%Caption formatting
\usepackage[small]{caption}
% src: https://tex.stackexchange.com/a/72981
%\usepackage[skip=0cm,list=true,labelfont=it]{subcaption}
\usepackage[list=true,labelfont=it,font=small]{subcaption}
#+end_src

* Formatting
- [[file:doc/1_Despacho_RT-31_2019-NormasFormatacaoTese.pdf][Normas formatacao tese]]

** Normas para a formatação gráfica
1. *Tipo de Letra*: NewsGotT
2. *Capas e respetivas contracapas*, dos trabalhos de Mestrado devem ter:
   - fundo branco,
   - verso da capa e da contracapa a cor cinza (pantone Cool Gray 7).
   - O lettering da capa e da lombada deve também ser cinza, no tipo de letra
     NewsGotT, e ter os tamanhos e formatações especificados no Manual.
3. *Todas as capas* devem ter a dimensão A4 e, de acordo com o Anexo 2, incluir:
   - o logótipo da Unidade Orgânica (UO) no âmbito do qual os trabalhos foram
   desenvolvidos. Este logótipo deve constar no topo da capa, ao centro da
   página. Integram o logótipo, para além dos símbolos, o lettering
   identificativo da UMinho e da UO;
   - nome completo do autor;
   - o título da Tese ou do trabalho de Mestrado;
   - mês e ano de submissão da Tese ou do trabalho de Mestrado.
4. *As lombadas*, de acordo com o Anexo 2, devem possuir:
   - o logótipo em formato vertical, e sem o lettering, da UO no âmbito do qual
     os trabalhos foram desenvolvidos;
   - o nome do autor (não necessariamente completo);
   - o título da Tese ou do trabalho de Mestrado;
   - a indicação "UMinho" e o ano de submissão da Tese.
5. Nas *contracapas*:
   - não existe obrigatoriedade de constar qualquer informação,
   - podendo, no entanto, ser utilizadas para a introdução de outros elementos
     tais como logótipos ou nomes de entidades que apoiaram ou financiaram os
     trabalhos (ex.: FCT, Erasmus, etc.).
     - Estas indicações devem, sempre que possível, constar a uma única cor
       (branco, no caso do fundo cinza; cinza, no caso do fundo branco) e no
       fundo da página (Anexo 2).
6. *Folha de rosto*: todos os trabalhos devem ter uma folha de rosto:
   1. branca,
   2. também com letteríng cinza,
   3. tipo de letra NewsGotT,
   4. com os tamanhos e formatações especificados no Manual.
   5. Nesta folha, também exemplificada no Anexo 2 devem constar os seguintes
      elementos:
      1. o logótipo da UO no âmbito do qual a Tese ou o trabalho de Mestrado foi
         desenvolvido.
	 Este logótipo deve constar no topo da folha, ao centro.
	 Integram o logótipo, para além dos símbolos, o lettering identificativo
         da UMinho e da respetiva UO;
      2. o nome completo do autor;
      3. o título da Tese ou do trabalho de Mestrado;
      4. o tipo trabalho, de acordo com o grau académico a obter ("Dissertação
         de Mestrado")
   6. o ramo do doutoramento e a respetiva especialidade (caso se aplique), no
      caso das Teses de Doutoramento,
      1. ou a indicação "Trabalho realizado sob a orientação do Professor",
         seguida do nome do orientador, devendo a redação ser adequada em termos
         de género;
   7. mês e ano de submissão da Tese ou do trabalho de Mestrado, ou, no caso de
      o candidato ser solicitado a introduzir correções na versão inicialmente
      entregue, antes ou depois das provas públicas, do mês e ano de entrega da
      versão corrigida.
7. *Verso da folha de rosto* (_Copyright_): Na página seguinte, deve constar a
   declaração    relativa às condições de utilização do trabalho por terceiros
   ou à eventual reprodução de partes do mesmo (*Anexo 3*).
8. *Agradecimentos* (_Acknowledgments_): Na folha 2 - página 3 do trabalho,
   devem constar:
   - os agradecimentos do autor, quando aplicável;
   - uma menção ao apoio financeiro, quando aplicável;
9. *Declaração de Integridade (Anexo 4)*: Na página seguinte (folha 2- página 4
   ou na folha 2- página 3, se não houver lugar a agradecimentos ou referência
   ao apoio financeiro) deve constar a Declaração de Integridade (Anexo 4).
10. *Abstract (pt)*: Na página seguinte deve constar o título e o resumo do
    trabalho, em português.
    1. *Palavras-chave*: No final do resumo, devem ser apresentadas três a cinco
       palavras chave, escritas por ordem alfabética.
    2. O resumo e as palavras chave deverão ter a _extensão máxima de uma
       página_.
11. *Abstract (en)*: Na página seguinte deve constar o título e o resumo do
    trabalho redigido em uma língua estrangeira de ampla divulgação.
    1. No final do resumo e na mesma língua, devem existir as palavras chave.
    2. Este resumo (incluindo as palavras chave) deverá ter uma extensão máxima
       de uma página.
12. Sempre que, mediante autorização expressa do Conselho Científico, o trabalho
    seja redigido em língua estrangeira, o resumo mencionado no ponto anterior
    deve ser redigido na mesma língua que o trabalho.
13. *Indice e listas*: De seguida deve ser apresentado:
    1. o índice, ao qual se seguem as
    2. listas de abreviaturas e siglas, de figuras,
    3. de símbolos,
    4. de ilustrações,
    5. de tabelas, etc., quando aplicável.
14. *Numeração*: Excetuando a folha de rosto, que não deve ser numerada, mas
    deve ser contada, todas as páginas de texto devem ser numeradas da seguinte
    forma:
    1. _as páginas iniciais ou preliminares_ - declarações, agradecimentos,
       resumos, índice, etc. - _devem ser numeradas_, preferencialmente ao fundo
       da página e ao centro, em _algarismos romanos minúsculos_;
    2. as páginas referentes a corpo do texto, referências bibliográficas e
       anexos e/ou apêndices devem ser numerados de forma contínua, também
       preferencialmente ao fundo da página e ao centro, mas em
       _algarismos árabes_.
15. *Layout*: O trabalho deve ser organizado:
    1. em _frente e verso_, em contínuo (sem páginas em branco),
    2. com _margens de 2,5cm_,
    3. usando a _fonte NewsGotT_:
       1. e uma _dimensão de 12_, /para a letra do texto/,
       2. e _de 8_, para a letra das /notas de rodapé/ (caso se aplique).
    4. _O espaçamento entre linhas_:
       1. deve ser de =1.5=,
       2. salvo nas referências bibliográficas e anexos onde pode ser
          considerado um espaçamento entre linhas de =1=.
16. *As tabelas, quadros, gráficos, figuras*, etc.:
    1. devem ser numerados, em cada caso, de 1 a N,
    2. e conter um titulo, sintético, que traduza claramente o respetivo
       conteúdo.
17. *Copyrifht de dados ou imagens de outros autores*:
    - não podem ser incluídos dados ou imagens que permitam identificar pessoas
      ou instituições,
    - pelo menos sem prévia autorização, escrita dos mesmos ou dos seus
      responsáveis legais,
    - a qual deve ser integrada no trabalho.
18. *Conceção das capas*: De modo a facilitar a conceção das capas:
    1. são disponibilizados na Intranet, mediante Login, ficheiros com a matriz
       das capas de Teses de Doutoramento (ou afim) e de trabalhos de Mestrado
       (a adaptar consoante o tipo de trabalho de Mestrado – Dissertação de
       Mestrado, Relatório de Estágio, Projeto ou outro), permitindo a
       edição/alteração direta do corpo do texto.
    2. São ainda disponibilizados outros elementos úteis no âmbito da preparação
       das capas e das respetivas folhas de rosto, tais como:
       1. os logótipos das várias UO
       2. ou o tipo de letra de utilização obrigatória.


*Summary*:
1) Capa
2) Contracapa
3) copyright
4) Acknowledgments
5) Statement of integrity
6) Quote (*Optional*)
7) Abstract (pt)
8) Abstract (en)
9) Index and lists
10) Chapters
  

** Normas para o depósito no RepositoriUM
Nos termos da legislação em vigor, existe obrigatoriedade legal de efetuar o
depósito de uma cópia digital das Teses de Doutoramento e dos trabalhos de
Mestrado num repositório integrante da rede do Repositório Científico de Acesso
Aberto de Portugal (RCAAP), como é o caso do RepositóriUM (Repositório
Institucional da Universidade do Minho).
- Este depósito visa o tratamento e a preservação dos trabalhos científicos
  mencionados, bem como a sua difusão em regime de acesso aberto,
  salvaguardando-se, no entanto, situações em que são aplicáveis restrições ou
  embargos.

  
1. No caso dos trabalhos de Mestrado, as Unidades Orgânicas (UO) procedem:
   1. no prazo máximo de 45 dias após a sua aprovação,
   2. ao registo dos trabalhos no RENATES
   3. e ao seu envio para os Serviços de Documentação (SDUM), em formato
      digital,
   4. acompanhadas:
      1. da declaração do autor de cada trabalho
      2. e do formulário constantes do anexo 4 ao presente despacho, a fim de
         dar cumprimento ao estabelecido na legislação em vigor.
2. Os SDUM procedem, no prazo máximo de 15 dias após a receção dos trabalhos de
   mestrado, ao seu depósito e ao registo dos respetivos metadados no
   RepositóriUM, que passam a incluir a classificação que lhe foi atribuída,
   comunicada pela UO responsável pela gestão do ciclo de estudos e no âmbito da
   qual a prova foi realizada
3. As referências e os metadados dos trabalhos ficam publicamente disponíveis
   no RepositóriUM imediatamente após o depósito do trabalho.
   1. O acesso ao conteúdo integral dos trabalhos é estabelecido nos termos
      definidos na licença a conceder pelo autor da Tese de doutoramento ou do
      trabalho de Mestrado, em conformidade com a Declaração constante do
      Anexo 5.
4. De acordo com a política de acesso aberto, recomenda-se que os autores
   autorizem a disponibilização dos seus trabalhos para acesso mundial,
   imediato.
   1. Em casos devidamente justificados, os autores podem solicitar que o
      trabalho fique, temporariamente, com um acesso mais restrito, através de
      um requerimento dirigido ao Reitor, a apresentar juntamente como o
      processo de requerimento de provas.
   2. Esse requerimento além identificar o autor, o(s) orientador(es), o curso e
      o trabalho, deve indicar a restrição de acesso pretendida e explicitar
      claramente as razões que justificam a necessidade desse estatuto de
      excecionalidade.
   3. Essas solicitações de excecionalidade deverão ser despachadas antes de ser
      efetuado o registo no RENATES e enviados os trabalhos para os SDUM.
5. A versão digital dos trabalhos deve obedecer às seguintes orientações:
   - Ser constituída, sempre que possível, por um único ficheiro;
   - Ser apresentada em formato PDF/A (componentes textuais)
   - Caso o trabalho inclua ficheiro(s) de imagem, áudio ou multimédia, estes
     devem ser também incluídos, preferencialmente em formatos normalizados e
     não-proprietários que constem da lista de formatos autorizados para efeitos
     de depósito no Repositório Científico de Acesso Aberto de Portugal (RCAAP)
     publicada no Despacho n.º 14167/2015
6. A versão digital dos trabalhos deverá passar a ser entregue em pen-drive,
   devidamente identificada.
7. Não será necessário incluir na pen-drive nem entregar os resumos,
   independentes, do trabalho mencionados em diversos artigos do Regulamento
   Académico da Universidade do Minho.
   

* Tools

** Notebooklm

* Research

** My thesis gaps
Research Gaps in Thesis on Trustworthy Open-Source Reference Software Stack for UAVs
Based on the provided excerpts from your thesis, here are some potential research gaps and areas for further exploration:

1) *Security and Safety Co-Design*: The sources emphasize the importance of
   security and safety for UAVs, particularly given the increasing regulations
   allowing them to operate over populated areas [1-3]. Your thesis aims to
   develop a trustworthy open-source software stack that prioritizes both
   security and safety [4], but the provided excerpts do not detail how these
   two aspects are co-designed.

   - *Gap*: How does the proposed software stack specifically address the
     interplay between security and safety, and what mechanisms are employed to
     ensure both aspects are met concurrently? [5]
   - For instance, how does the system handle failures that could compromise
     safety while also preventing malicious exploitation of those failures?
   - Exploring the trade-offs between security and safety, especially in
     resource-constrained UAV environments, could be valuable.

2) *Static Partitioning Challenges*: You choose Bao, a static partitioning
   hypervisor, for its security and real-time guarantees [6-8]. However, the
   sources acknowledge challenges associated with static partitioning,
   particularly regarding resource sharing and potential side-channel attacks
   [6, 9].

   - *Gap*: How does the proposed software stack mitigate the limitations of
     static partitioning in practice, and what measures are taken to ensure
     robust isolation between partitions and prevent side-channel
     vulnerabilities?
   - Investigating advanced partitioning techniques, such as memory bandwidth
     reservation or cache partitioning beyond coloring, could be beneficial [6,
     9].
   - Evaluating the effectiveness of these techniques in terms of performance
     and security would strengthen the thesis.

3) *Open-Source Software Stack Evaluation*: The thesis aims to develop an
   open-source software stack, but the excerpts lack a detailed evaluation of
   its performance, security, and safety features [4].

   - *Gap*: How does the developed software stack compare to existing open-source
     and commercial solutions in terms of performance, security, and safety?
     [10-12]
   - Conducting a comparative analysis, including benchmark tests and
	 vulnerability assessments, would provide evidence for the claimed advantages
	 of the proposed stack.

4) *Real-World Applicability and Validation*: The thesis focuses on developing a
   trustworthy software stack, but the excerpts do not discuss its real-world
   applicability and validation [4].

   - *Gap*: How is the developed software stack validated in realistic UAV scenarios,
	 and what are the practical implications and limitations of its deployment?
   - Testing the software stack on different UAV platforms and in diverse
	 operational environments would demonstrate its practicality and robustness.
   - Addressing potential challenges related to integration, deployment, and
     maintenance would further enhance the research's impact.

5) *Specific Security Mechanisms*: While the thesis mentions security as a primary
   goal, it lacks details about the specific security mechanisms implemented in
   the software stack [4, 13].

   - *Gap*: What concrete security features are incorporated into the software stack,
	 and how do they address identified UAV security threats? [1, 14, 15]
   - Elaborating on the chosen security primitives, such as authentication
	 protocols, encryption techniques, or intrusion detection systems, would
	 clarify the system's security posture.
   - Analyzing the effectiveness of these mechanisms against known attack vectors
	 would solidify the security claims.

6) *OTA Update Security*: The thesis mentions remote updates through an OTA
   mechanism but does not elaborate on the security considerations of this
   process [13].

   - *Gap*: How are OTA updates secured to prevent malicious manipulation or
	 unauthorized modifications?
   - Describing the security measures employed, such as code signing, secure
	 communication channels, and rollback mechanisms, would be essential to ensure
	 the trustworthiness of updates.

7) *Inter-VM Communication Security*: Bao offers a basic mechanism for inter-VM
   communication [16], which is crucial in a multi-partition system. However,
   the security aspects of this communication are not explicitly addressed.

 - *Gap*: How does the software stack secure communication channels between VMs to
   prevent information leakage or unauthorized access?
 - Discussing secure inter-partition communication mechanisms, potentially
   leveraging hardware isolation features, would strengthen the overall security
   of the system.
 - By addressing these research gaps and providing a more detailed and
   comprehensive analysis of the proposed software stack's performance,
   security, and safety, you can significantly enhance the value and impact of
   your MSc thesis.

* Writing
** ✔ DONE Title
:LOGBOOK:
- State "✔ DONE"     from              [2022-12-22 Thu 21:04]
:END:
   Trustworthy Open-Source Reference Software Stack for UAV applications
** Abstract
** ✔ DONE Ask for permissions for figures https://www.researchgate.net/post/Do_I_need_a_permission_to_copy_any_figure_from_a_research_article_for_my_review_article/5de8fdb7f0fb623dd7346896/citation/download
   :LOGBOOK:
   - State "✔ DONE"     from "☛ TODO"     [2022-04-26 Tue 06:48]
   - State "☛ TODO"     from              [2022-04-25 Mon 08:15]
   :END:
*** Licence footnote
    #+begin_src latex
\begin{figure}[!hbt]
  \centering
    \includegraphics[width=0.3\textwidth]{./img/svg-slice-example.png}%
    \caption[SVG slice example]{SVG slice example~\cite{slic3rSvg}\footnotemark}%
      %\fnref{foot:cc-lic}}%
      %\textsuperscript{\ref{foot:cc-lic}}%
    \label{fig:svg-slice-example}
\end{figure}
%
\footnotetext{\label{foot:cc-lic}Used under the terms of the Creative Commons BY-SA 3.0 licence.}%

This uses the same note\fnref{foot:cc-lic};
    #+end_src
** ✔ DONE Chapter style
:LOGBOOK:
- State "✔ DONE"     from              [2024-05-07 ter 02:28]
:END:
   % The chapter style to be used
 You can use any of the default memoir style files:
 #+begin_example
     [ default, section, hangnum, article, bianchi,
       bringhurst, brotherton, chappell, crosshead,
       culver, dash, demo2, dowding, ell, ger,
       komalike, lyhne , madsen, ntglike, southall,
       tandh, thatcher, veelo, verville, wilsondob ]
 #+end_example
 
 Or any of the additional styles
 #+begin_example
     [ bar-compact, bar, bluebox, compact, elegant,
       fmv, hansen, ist, vz34, vz43 ]
 #+end_example

 I already tested this.
 - The result can be seen in [[file:doc/chapters_styles.pdf][ChaptersStyles]]


 I used the default: =bar=


       
** Intro [1/4]
- [ ] Context
- [ ] Motivation
- [X] Goals
- [ ] Document structure
** State of the Art [1/6]
1) [X] Mixed criticality
   - [X] Virtualizacao como tecnologia
   - [X] Supervisores/Bao
2) [ ] UAVs
   1) [ ] Definition ([[id:334F0101-8105-4371-B4D5-2931ED1F791F][src]])
   2) [ ] Background and history of UAVs ([[id:D3D4BD81-83E1-4416-96E9-C8995A345BF7][src]])
   3) [ ] Market ([[id:F55021FF-0926-4272-B6D8-DF4178C79ED7][src]])
   4) [ ] Applications ([[id:334F0101-8105-4371-B4D5-2931ED1F791F][src]])
   5) [ ] Classifications ([[id:334F0101-8105-4371-B4D5-2931ED1F791F][src]], [[id:F55021FF-0926-4272-B6D8-DF4178C79ED7][src]])
   6) [ ] Regulations ([[id:334F0101-8105-4371-B4D5-2931ED1F791F][src]], [[file:~/OneDrive - Universidade do Minho/Documents/Univ/MI_Electro/Tese/Papers/SoK-SecurityAndPrivacyIntheAgeOfCommercialDrones.pdf::%PDF-1.5][src]])
   7) [ ] Characteristics ([[id:F55021FF-0926-4272-B6D8-DF4178C79ED7][src]])
   8) [ ] Functional hierarchy, Structure of a UAV system, Components and system
 telecommunications in remote areas ;
      architecture ([[id:E74C5DFF-D2E8-4AF4-A694-043D0FA813BA][src]], [[id:403BBCCA-0249-452C-8F69-DD931A34173E][src]], [[id:9BE3E921-FD5E-4A32-9E34-6B1B097299AC][src]], [[id:D2AD5333-0676-4C84-9E6B-47F47753EBC4][src]])
   9) [ ] Network comm architecture ([[id:E74C5DFF-D2E8-4AF4-A694-043D0FA813BA][src]])
   10) [ ] Communications protocols ([[id:E74C5DFF-D2E8-4AF4-A694-043D0FA813BA][src]])
   11) [ ] Cybersecurities vulnerabilities, attacks, mitigations ([[id:0CF6B2C5-CBBD-42DB-B926-B6168D1AD2A2][src]], [[id:1B1A2FE1-2E63-4D83-AA11-54A0A0133D3B][src]], [[id:F55021FF-0926-4272-B6D8-DF4178C79ED7][src]])
   12) [ ] Security and privacy ([[id:0CF6B2C5-CBBD-42DB-B926-B6168D1AD2A2][src]])
   13) [ ] General structure of existing SW ([[id:915C248C-4762-4BA3-ACB6-F5E5EC4DB64E][src]])
   14) [ ] Comparison of FCS and its features  ([[id:915C248C-4762-4BA3-ACB6-F5E5EC4DB64E][src]])
   15) [ ] Analysis of the open-source SW modules ([[id:915C248C-4762-4BA3-ACB6-F5E5EC4DB64E][src]])
   16) [ ] Aircraft selection ([[id:8CCE1A69-5464-4342-823C-B4510F26B396][src]])
   17) [ ] Safety failures ([[id:2060592A-9AD8-4D87-8BCB-EED98E8B7DC8][src]])
3) [ ] HW platforms para drones
   1) [ ] Architectures for UAVs ([[id:2060592A-9AD8-4D87-8BCB-EED98E8B7DC8][src]])
      1) [ ] Comparative analysis ([[id:2060592A-9AD8-4D87-8BCB-EED98E8B7DC8][src]])
   2) [ ] Open-source HW ([[id:403BBCCA-0249-452C-8F69-DD931A34173E][src]], [[eww:][src]])
   3) [ ] Comparison of COTS UAVs ([[id:8CCE1A69-5464-4342-823C-B4510F26B396][src]])
4) [ ] SW platforms
   1) [ ] Open-source SW ([[id:403BBCCA-0249-452C-8F69-DD931A34173E][src]], [[id:D2AD5333-0676-4C84-9E6B-47F47753EBC4][src]])
   2) [ ] Analysis of the open-source SW modules ([[id:915C248C-4762-4BA3-ACB6-F5E5EC4DB64E][src]])
   3) [ ] General structure of existing SW ([[id:915C248C-4762-4BA3-ACB6-F5E5EC4DB64E][src]])
   4) [ ] Comparison of FCS and its features  ([[id:915C248C-4762-4BA3-ACB6-F5E5EC4DB64E][src]])
5) [ ] Related work
   1) [ ] List of UAVs surveys, their challenges and focus ([[id:F55021FF-0926-4272-B6D8-DF4178C79ED7][src]])
   2) [ ] Future research directions of UAVs ([[id:F55021FF-0926-4272-B6D8-DF4178C79ED7][src]])
   3) [ ] Virtualization solution for UAV AI applications ([[id:D6DB242E-FB99-4DC1-A733-76CA540C173C][src]])
6) [ ] Final Remarks
*** UAV Intro
[[file:~/Documents/Univ/MI_Electro/Tese/Papers/An-Overview-of-the-Drone-Open-Source-Ecosystem.pdf::%PDF-1.7][src]]
PX4 also supports Unmanned Vehicles (UV) beyond
aerial systems including Unmanned Ground Vehicles
(UGV), Unmanned Surface Vehicles (USV) (e.g., boats) and
Unmanned Under Water Vehicles (UUV).

[[file:~/OneDrive - Universidade do Minho/Documents/Univ/MI_Electro/Tese/Papers/UAVs-ComprehensiveReview-2022.pdf::%PDF-1.7][src]]
-------------------
In recent years, UAVs have gained significant attention. Generally, UAVs refer
to controlled aerial vehicles without carrying a human pilot on them. It can be
autonomously controlled and operated through sensors, microprocessors and other
electronic gadgets [35].

Figure 1 depicts a typical UAV system architecture, showing how UAVs interact with
satellites, ground control systems (GCS), smart phones, and computers via communication
links. A human operator is used to control and operate a UAV remotely. UAVs can perform
autonomous tasks in situations where human intervention is difficult or dangerous [36].
At present, UAVs have become a very convenient approach for logistics. In particular,
there is a notable upsurge in the civilian market for UAVs. The key applications of UAVs
include remote operations such as search and rescue, disaster monitoring, environmental
monitoring, and delivery of airmail, medical items, and packages. Figure 2 presents the
growing revenue of USA for commercial UAV market in different sectors.

Despite increasing attention, mostly UAVs are being controlled by human-aided
remote controls. Generally, UAVs’ characteristics, configurations, and
mechanisms vary according to the application, speed, weight, and
operation.
- Figure 3 shows different types of aircraft in terms of thrust forces and
  flight principles [38].
- Piloting a UAV is hard for human beings while manual controls are vulnerable
  to inconvenience, inefficiency, and human error.

*Vertical TakeOff and Landing (VTOL)*
- key feature of UAVs
- high speed
- high efficiency
- vertical hanging capability in the air
- Example: Blimp

-------------------
*** Security concerns
2017, USA: banned the Dji drones for cybersecurity concerns
https://www.thedronegirl.com/2017/08/18/dji-follows-u-s-army-ban-new-stealth-mode/

*Security is not part of design*
UAVs often include onboard wireless communication modules that use open,
unencrypted, and unauthenticated channels, exposing them to a variety of
cyber-attacks[112-114] ([[file:~/Documents/Univ/MI_Electro/Tese/Papers/UAVs-ComprehensiveReview-2022.pdf::%PDF-1.7][UAV-ComprehensiveReview]])

*Hacking of drones* is another major concerns of using UAVs for data collection
and wireless delivery. ([[file:~/Documents/Univ/MI_Electro/Tese/Papers/UAVs-ComprehensiveReview-2022.pdf::%PDF-1.7][UAV-ComprehensiveReview]])
- Military operations

*Denial-of-Service* (DoS) and Distributed Dos (DDoS) are the most common attacks
on UAVs. ([[file:~/Documents/Univ/MI_Electro/Tese/Papers/UAVs-ComprehensiveReview-2022.pdf::%PDF-1.7][UAV-ComprehensiveReview]])
- Cause severe availability challenges as the challenger sends several requests
  to cause UAV network congestion
- DoS attacks are performed by:
  - depleting the batteries,
  - overloading the processing units
  - and flooding the comm links to cause huge interruptions

*GPS Spoofing attack*: inserting or passing false data through the GPS miscreant

*Ground Control System attacks*
- Very dangerous because the attacker can steal all the data from UAV
- Enables the adversary to send malicious and erroneous commands
- Usually performed through key loggers, viruses and malwares

*Malicious HW attack* [118] ([[file:~/Documents/Univ/MI_Electro/Tese/Papers/UAVs-ComprehensiveReview-2022.pdf::%PDF-1.7][UAV-ComprehensiveReview]])
- goal: steak confidential data or cause a failure in UAVs mission
- Any attack to interrupt UAVs flight control and comm links to modify mission
  parameters is known as *flight control computer attack*.
  - Can be mitigated through onboard SW and HW mechanisms, such as, RT
    monitoring, instantaneous estimation of the controller, alert warning and
    immediate action on any alteration from the intended controller model.



*** Diagrams UAV
1) uav.pu: Concept, History, Market, Applications, Characteristics, Regulations,
   Classifications
2) uav2.pu: UAV System Overview - Tasks, Components, Functional Hierarchy, Sys
   Arch, HW, SW, Network Comm
3) uav2-1.pu: UAV Sys Overview - Tasks, Components
4) uav2-2.pu: UAV Sys Overview - Functional Hierarchy
5) uav2-3.pu: UAV Sys Overview - FCS Arch, HW, SW, Network Comm
6) uav3.pu: UAV Security and Safety

*** Autopilot
*Autopilot shortcomings*:
  - limited battery life
  - limited autonomy
  - landing accuracy (can be improved through CV techniques, but needs resources
    and protocols that are not available for commercial drones)
  - limited mission time and distance

*** PX4
The flight controller runs the normal PX4 flight stack, while a companion computer provides advanced features like object avoidance and collision prevention. The two systems are connected using a fast serial or IP link, and typically communicate using the MAVLink protocol (opens new window). Communications with the ground stations and the cloud are usually routed via the companion computer (e.g. using the MAVLink Router

(opens new window) (from Intel)).

PX4 systems typically run a Linux OS on the companion computer (because the PX4/PX4-Avoidance
(opens new window) project delivers ROS-based avoidance libraries designed for Linux). Linux is a much better platform for "general" software development than NuttX; there are many more Linux developers and a lot of useful software has already been written (e.g. for computer vision, communications, cloud integrations, hardware drivers). Companion computers sometimes run Android for the same reason.

